// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful"

export interface ICarouselFields {
    /** Title */
    title: string

    /** Slug */
    slug: string

    /** Image */
    image: Asset
}

/** Homepage carousel */

export interface ICarousel extends Entry<ICarouselFields> {
    sys: {
        id: string
        type: string
        createdAt: string
        updatedAt: string
        locale: string
        contentType: {
            sys: {
                id: "carousel"
                linkType: "ContentType"
                type: "Link"
            }
        }
    }
}

export interface IFeaturedFields {
    /** Title */
    title: string

    /** Subtitle */
    subtitle: string

    /** Slug */
    slug?: string | undefined

    /** Images */
    images: Asset[]
}

/** Featured project images */

export interface IFeatured extends Entry<IFeaturedFields> {
    sys: {
        id: string
        type: string
        createdAt: string
        updatedAt: string
        locale: string
        contentType: {
            sys: {
                id: "featured"
                linkType: "ContentType"
                type: "Link"
            }
        }
    }
}

export interface IProfileFields {
    /** Title */
    title: string

    /** Pictures */
    pictures: Asset[]
}

/** All profile pictures of the photographer */

export interface IProfile extends Entry<IProfileFields> {
    sys: {
        id: string
        type: string
        createdAt: string
        updatedAt: string
        locale: string
        contentType: {
            sys: {
                id: "profile"
                linkType: "ContentType"
                type: "Link"
            }
        }
    }
}

export interface IServicesFields {
    /** Title */
    title: string

    /** Slug */
    slug: string

    /** Description */
    description: string

    /** Cost */
    cost: number

    /** Thumbnail */
    thumbnail?: Asset | undefined
}

/** Barelens Services */

export interface IServices extends Entry<IServicesFields> {
    sys: {
        id: string
        type: string
        createdAt: string
        updatedAt: string
        locale: string
        contentType: {
            sys: {
                id: "services"
                linkType: "ContentType"
                type: "Link"
            }
        }
    }
}

export type CONTENT_TYPE = "carousel" | "featured" | "profile" | "services"

export type IEntry = ICarousel | IFeatured | IProfile | IServices

export type LOCALE_CODE = "en-US"

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US"
