name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  DIRECTUS_DOCKER_DOMAIN: ${{ secrets.DIRECTUS_DOCKER_DOMAIN }}
  DIRECTUS_DOCKER_TOKEN: ${{ secrets.DIRECTUS_DOCKER_TOKEN }}
  DIRECTUS_DOCKER_PASSWORD: ${{ secrets.DIRECTUS_DOCKER_PASSWORD }}
  DIRECTUS_EMAIL: ${{ secrets.DIRECTUS_EMAIL }}
  REVALIDATE_TOKEN: ${{ secrets.REVALIDATE_TOKEN }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
